services:
  bot:
    build:
      context: ./ProductTrackerBot
      dockerfile: Dockerfile
    env_file:
      - ./.env.dev
    environment:
      - DB_PATH=/data/product-tracker.db
    volumes:
      - db-data-dev:/data
    restart: unless-stopped
    networks:
      - internal-dev

volumes:
  db-data-dev:

networks:
  internal-dev:
    driver: bridge
