// <copyright file="LoginCommandHandler.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace ProductTrackerBot.Handlers;

using ProductTrackerBot.Localization;
using ProductTrackerBot.Services;
using Telegram.Bot;
using Telegram.Bot.Types;

/// <summary>
/// Handles the /login command — verifies a one-time code generated by the web login page.
/// </summary>
public class LoginCommandHandler : ICommandHandler
{
    private readonly ITelegramBotClient botClient;
    private readonly ILocalizer localizer;
    private readonly LoginCodeStore loginCodeStore;

    /// <summary>
    /// Initializes a new instance of the <see cref="LoginCommandHandler"/> class.
    /// </summary>
    public LoginCommandHandler(
        ITelegramBotClient botClient,
        ILocalizer localizer,
        LoginCodeStore loginCodeStore)
    {
        this.botClient = botClient;
        this.localizer = localizer;
        this.loginCodeStore = loginCodeStore;
    }

    /// <inheritdoc/>
    public string Command => "/login";

    /// <inheritdoc/>
    public string? Description => null;

    /// <inheritdoc/>
    public async Task HandleAsync(Message message, CancellationToken cancellationToken)
    {
        var chatId = message.Chat.Id;
        var parts = message.Text?.Split(' ', 2) ?? [];

        if (parts.Length < 2 || string.IsNullOrWhiteSpace(parts[1]))
        {
            await this.botClient.SendMessage(
                chatId: chatId,
                text: this.localizer.Get(chatId, "login.usage"),
                cancellationToken: cancellationToken);
            return;
        }

        var code = parts[1].Trim();
        var reply = this.loginCodeStore.TryVerify(code, chatId)
            ? this.localizer.Get(chatId, "login.success")
            : this.localizer.Get(chatId, "login.invalid");

        await this.botClient.SendMessage(
            chatId: chatId,
            text: reply,
            cancellationToken: cancellationToken);
    }
}
